[TASK] Always use PHPUnit 9
TYPO3-Documentation/fluid-documentation-generator pull request #11
Opened 2023-02-25 12:19 UTC by linawolf

Remove deprecations in preparations for PHPUnit 10

2023-02-25 18:34 UTC, brotkrueml requested changes
Please also migrate the phpunit configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
        bootstrap="vendor/autoload.php"
>
    <coverage>
        <include>
            <directory>src/</directory>
        </include>
        <report>
            <clover outputFile="build/logs/clover.xml"/>
        </report>
    </coverage>
    <testsuites>
        <testsuite name="FluidDocumentationGenerator">
            <directory>tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

Haven't the permissions to add commits to PRs.

2023-02-26 07:55 UTC, linawolf commented
@brotkrueml I added this repository to the Active Documentation Members, you should have Maintainer rights now

2023-02-26 08:42 UTC, linawolf commented
And applied the changes you suggested

2023-02-26 09:43 UTC, brotkrueml approved these changes

2023-02-26 10:17 UTC, DavidBruchmann approved these changes

2023-02-27 11:38 UTC, merged